[build]
  publish = "client/dist"
  command = "cd client && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/games"
  to = "/.netlify/functions/games"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
